package(default_visibility=["//visibility:public"])

cc_library(
  name = "physics_scene",
  srcs = [
    "angry_bunny_scene.h",
    "angry_bunny_scene.cc",
  ],
  deps = [
    "//physics:physics",
    "//renderer:renderer",
    "@fmt",
    "@glm",
    "@imgui",
  ],
)