package(default_visibility=["//visibility:public"])
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library(
  name = "path_tracing",
  srcs = [
    "path_tracing.h",
    "path_tracing.cc",
  ],
  deps = [
  ]
)