package(default_visibility=["//visibility:public"])
load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//:cg_proto_library.bzl", "cg_proto_library")

cg_proto_library(
  name = "config_proto",
  srcs = [ "config.proto" ],
)