package(default_visibility=["//visibility:public"])

cc_library(
  name = "geometry_scene",
  srcs = [
    "fitting_scene.h",
    "fitting_scene.cc",
    "implot_demo_scene.h",
    "implot_demo_scene.cc",
  ],
  deps = [
    "//base:base",
    "//geometry:geometry",
    "//renderer:renderer",
    "@eigen",
    "@glm",
    "@imgui",
  ],
)