package(default_visibility=["//visibility:public"])
load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_library (
  name = "render_graph",
  srcs = [
    "render_graph.h",
    "render_graph.cc",
  ],
  deps = [
    "//engine:debug",
  ],
)