cc_test (
  name = "eigen_test",
  srcs = [
    "eigen_test.cc",
  ],
  deps = [
    "//renderer:renderer",
    "//renderer:util",
    "@eigen",
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "@glew",
    "@glm",
  ],
)

cc_test (
  name = "geometry_test",
  srcs = [
    "geometry_test.cc",
  ],
  deps = [
    "//renderer:renderer",
    "//renderer:util",
    "@eigen",
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "@glew",
    "@glm",
  ],
)

cc_test (
  name = "renderer_test",
  srcs = [
    "renderer_test.cc",
  ],
  deps = [
    "//renderer:renderer",
    "//renderer:util",
    "@gtest//:gtest",
    "@gtest//:gtest_main",
    "@glew",
    "@glm",
  ],
)